In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"D:\data-science\projects\APS-fault-detection\aps_failure_training_set1.csv")
df.head()

class  aa_000 ab_000 ac_000 ad_000 ae_000 af_000 ag_000  ag_001   ag_002  \
0   pos  153204      0    182     na      0      0      0       0        0   
1   pos  453236     na   2926     na      0      0      0       0      222   
2   pos   72504     na   1594   1052      0      0      0     244   178226   
3   pos  762958     na     na     na     na     na    776  281128  2186308   
4   pos  695994     na     na     na     na     na      0       0        0   

   ...   ee_002   ee_003   ee_004   ee_005   ee_006  ee_007  ee_008 ee_009  \
0  ...   129862    26872    34044    22472    34362       0       0      0   
1  ...  7908038  3026002  5025350  2025766  1160638  533834  493800   6914   
2  ...  1432098   372252   527514   358274   332818  284178    3742      0   
3  ...       na       na       na       na       na      na      na     na   
4  ...  1397742   495544   361646    28610     5130     212       0      0   

  ef_000 eg_000  
0      0      0  
1      0      0  
2      0      0  
3     na     na  
4     na     na  

[5 rows x 171 columns]

In [5]:
rep = df.isna().sum().div(df.shape[0])
rep

class     0.000000
aa_000    0.000000
ab_000    0.770863
ac_000    0.059163
ad_000    0.254228
            ...   
ee_007    0.010473
ee_008    0.010473
ee_009    0.010473
ef_000    0.047806
eg_000    0.047778
Length: 171, dtype: float64

In [8]:
rep[rep>0.3]

ab_000    0.770863
bk_000    0.381977
bl_000    0.451393
bm_000    0.655190
bn_000    0.727617
bo_000    0.765337
bp_000    0.787941
bq_000    0.805018
br_000    0.814110
cr_000    0.770863
dtype: float64

In [11]:
cols_to_drop = rep[rep>0.3].index
list(cols_to_drop)

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [14]:
len(cols_to_drop)

10

In [2]:
df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [11]:
x = list(df["class"].value_counts().index)
x.sort()
x

['neg', 'pos']

In [6]:
df["class"].value_counts().values

array([35188,  1000], dtype=int64)

In [9]:
x == ['pos', 'neg']

False

In [12]:
y = ['pos', 'neg']
y

['pos', 'neg']

In [13]:
y.sort()

In [14]:
y

['neg', 'pos']

In [15]:
y.sort() == x.sort()

True

In [19]:
["pos", "neg"].sort() == ["neg", "pos"].sort()

True

In [5]:
df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [8]:
len([col for col in df.columns if df[col].dtypes == 'O'])

170

In [13]:
df.replace({'na': np.NAN}, inplace=True)

In [18]:
df = df.drop(["class"], axis=1).astype('float')

In [19]:
df.dtypes

aa_000    float64
ab_000    float64
ac_000    float64
ad_000    float64
ae_000    float64
           ...   
ee_007    float64
ee_008    float64
ee_009    float64
ef_000    float64
eg_000    float64
Length: 170, dtype: object

In [22]:
import os

path = r"D:\data-science\projects\APS-fault-detection\artifacts\12062022__141811\data validation\report.yaml"
path

'D:\\data-science\\projects\\APS-fault-detection\\artifacts\\12062022__141811\\data validation\\report.yaml'

In [23]:
os.path.basename(path)

'report.yaml'

In [24]:
os.path.dirname(path)

'D:\\data-science\\projects\\APS-fault-detection\\artifacts\\12062022__141811\\data validation'

In [27]:
import yaml
import logging as lg

def write_yaml_file(file_path: str, data: dict, desc: str):
        """Dumps the desired data into `yaml` file at the said location.

        Args:
            file_path (str): Location where yaml file is to be created.
            data (dict): Data that is to be dumped into yaml file.
            desc (str): Description of the file.
        """
        try:
            lg.info(f"readying the `{desc}` yaml file..")
            file_dir = os.path.dirname(file_path)
            os.makedirs(file_dir, exist_ok=True)
            with open(file_path, "w") as f:
                yaml.dump(data, f)
            ...
        except Exception as e:
            lg.exception(e)

In [28]:
write_yaml_file()

'D:\\data-science\\projects\\APS-fault-detection\\artifacts\\12062022__141811\\data validation\\report.yaml'

In [5]:
from src.utils.file_operations import BasicUtils

feat, lab = BasicUtils().get_features_and_labels(df, target=["class"])

In [6]:
feat

aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000  ag_001   ag_002  \
0      153204      0         182     na      0      0      0       0        0   
1      453236     na        2926     na      0      0      0       0      222   
2       72504     na        1594   1052      0      0      0     244   178226   
3      762958     na          na     na     na     na    776  281128  2186308   
4      695994     na          na     na     na     na      0       0        0   
...       ...    ...         ...    ...    ...    ...    ...     ...      ...   
36183  153002     na         664    186      0      0      0       0        0   
36184    2286     na  2130706538    224      0      0      0       0        0   
36185     112      0  2130706432     18      0      0      0       0        0   
36186   80292     na  2130706432    494      0      0      0       0        0   
36187   40222     na         698    628      0      0      0       0        0   

        ag_003  ...   ee_002   ee_003   ee_004   ee_005   ee_006  ee_007  \
0        11804  ...   129862    26872    34044    22472    34362       0   
1       323436  ...  7908038  3026002  5025350  2025766  1160638  533834   
2      1249396  ...  1432098   372252   527514   358274   332818  284178   
3      8123016  ...       na       na       na       na       na      na   
4        55620  ...  1397742   495544   361646    28610     5130     212   
...        ...  ...      ...      ...      ...      ...      ...     ...   
36183     2564  ...   998500   566884  1290398  1218244  1019768  717762   
36184        0  ...    10578     6760    21126    68424      136       0   
36185        0  ...      792      386      452      144      146    2622   
36186        0  ...   699352   222654   347378   225724   194440  165070   
36187        0  ...   440066   183200   344546   254068   225148  158304   

       ee_008  ee_009 ef_000 eg_000  
0           0       0      0      0  
1      493800    6914      0      0  
2        3742       0      0      0  
3          na      na     na     na  
4           0       0     na     na  
...       ...     ...    ...    ...  
36183  898642   28588      0      0  
36184       0       0      0      0  
36185       0       0      0      0  
36186  802280  388422      0      0  
36187  170384     158      0      0  

[36188 rows x 170 columns]

In [8]:
lab

class
0       pos
1       pos
2       pos
3       pos
4       pos
...     ...
36183   neg
36184   neg
36185   neg
36186   neg
36187   neg

[36188 rows x 1 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_label = df[["class"]]
label_encoder.fit(df_label)

c:\Users\Admin\anaconda3\envs\sensor\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [19]:
df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [4]:
df_train = pd.read_csv(r"D:\data-science\projects\APS-fault-detection\artifacts\12072022__103501\data_ingestion\training_set.csv")
df_train.head()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg     640     0.0     4.0     6.0     0.0     0.0     0.0     0.0   
1   neg     180     NaN    40.0    40.0     0.0     0.0     0.0     0.0   
2   neg   39336     NaN   630.0   458.0     0.0     0.0     0.0     0.0   
3   neg   29256     NaN   720.0   684.0     0.0     0.0     0.0     0.0   
4   neg   28988     NaN     0.0     NaN     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005    ee_006   ee_007  \
0     0.0  ...    2940.0    1094.0    1822.0    3056.0    3814.0  13740.0   
1     0.0  ...    2492.0     794.0    1172.0    3328.0      12.0      0.0   
2     0.0  ...  417352.0  237644.0  510714.0  338544.0  167132.0  73462.0   
3     0.0  ...  347250.0  233994.0  520920.0  191080.0   59730.0  29486.0   
4     0.0  ...  223524.0  138916.0  411678.0  471378.0  112360.0   2268.0   

    ee_008  ee_009  ef_000  eg_000  
0    452.0     0.0     0.0     0.0  
1      0.0     0.0     0.0     0.0  
2  81896.0  7204.0     0.0     0.0  
3  30016.0   262.0     0.0     0.0  
4     26.0     0.0     0.0     0.0  

[5 rows x 171 columns]

In [17]:
df_train.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [20]:
num_atts = [col for col in df.columns if df_train[col].dtypes != 'O']
cat_atts = [col for col in df.columns if df_train[col].dtypes == 'O']

num_atts

['aa_000',
 'ab_000',
 'ac_000',
 'ad_000',
 'ae_000',
 'af_000',
 'ag_000',
 'ag_001',
 'ag_002',
 'ag_003',
 'ag_004',
 'ag_005',
 'ag_006',
 'ag_007',
 'ag_008',
 'ag_009',
 'ah_000',
 'ai_000',
 'aj_000',
 'ak_000',
 'al_000',
 'am_0',
 'an_000',
 'ao_000',
 'ap_000',
 'aq_000',
 'ar_000',
 'as_000',
 'at_000',
 'au_000',
 'av_000',
 'ax_000',
 'ay_000',
 'ay_001',
 'ay_002',
 'ay_003',
 'ay_004',
 'ay_005',
 'ay_006',
 'ay_007',
 'ay_008',
 'ay_009',
 'az_000',
 'az_001',
 'az_002',
 'az_003',
 'az_004',
 'az_005',
 'az_006',
 'az_007',
 'az_008',
 'az_009',
 'ba_000',
 'ba_001',
 'ba_002',
 'ba_003',
 'ba_004',
 'ba_005',
 'ba_006',
 'ba_007',
 'ba_008',
 'ba_009',
 'bb_000',
 'bc_000',
 'bd_000',
 'be_000',
 'bf_000',
 'bg_000',
 'bh_000',
 'bi_000',
 'bj_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'bs_000',
 'bt_000',
 'bu_000',
 'bv_000',
 'bx_000',
 'by_000',
 'bz_000',
 'ca_000',
 'cb_000',
 'cc_000',
 'cd_000',
 'ce_000',
 

In [21]:
cat_atts

['class']

In [22]:
df.dtypes

class     object
aa_000     int64
ab_000    object
ac_000    object
ad_000    object
           ...  
ee_007    object
ee_008    object
ee_009    object
ef_000    object
eg_000    object
Length: 171, dtype: object

In [23]:
df_train.dtypes

class      object
aa_000      int64
ab_000    float64
ac_000    float64
ad_000    float64
           ...   
ee_007    float64
ee_008    float64
ee_009    float64
ef_000    float64
eg_000    float64
Length: 171, dtype: object

In [3]:
arr = np.asarray(df)
arr

array([['pos', 153204, '0', ..., '0', '0', '0'],
       ['pos', 453236, 'na', ..., '6914', '0', '0'],
       ['pos', 72504, 'na', ..., '0', '0', '0'],
       ...,
       ['neg', 112, '0', ..., '0', '0', '0'],
       ['neg', 80292, 'na', ..., '388422', '0', '0'],
       ['neg', 40222, 'na', ..., '158', '0', '0']], dtype=object)

In [4]:
arr.shape

(36188, 171)

In [3]:
df.dtypes

class     object
aa_000     int64
ab_000    object
ac_000    object
ad_000    object
           ...  
ee_007    object
ee_008    object
ee_009    object
ef_000    object
eg_000    object
Length: 171, dtype: object

### # Transformation:

In [4]:
sensors = pd.read_csv(r"D:\data-science\projects\APS-fault-detection\artifacts\12082022__111422\data_ingestion\sensors_feature_store.csv")
sensors.head()

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000    ag_001  \
0   pos  153204     0.0   182.0     NaN     0.0     0.0     0.0       0.0   
1   pos  453236     NaN  2926.0     NaN     0.0     0.0     0.0       0.0   
2   pos   72504     NaN  1594.0  1052.0     0.0     0.0     0.0     244.0   
3   pos  762958     NaN     NaN     NaN     NaN     NaN   776.0  281128.0   
4   pos  695994     NaN     NaN     NaN     NaN     NaN     0.0       0.0   

      ag_002  ...     ee_002     ee_003     ee_004     ee_005     ee_006  \
0        0.0  ...   129862.0    26872.0    34044.0    22472.0    34362.0   
1      222.0  ...  7908038.0  3026002.0  5025350.0  2025766.0  1160638.0   
2   178226.0  ...  1432098.0   372252.0   527514.0   358274.0   332818.0   
3  2186308.0  ...        NaN        NaN        NaN        NaN        NaN   
4        0.0  ...  1397742.0   495544.0   361646.0    28610.0     5130.0   

     ee_007    ee_008  ee_009  ef_000  eg_000  
0       0.0       0.0     0.0     0.0     0.0  
1  533834.0  493800.0  6914.0     0.0     0.0  
2  284178.0    3742.0     0.0     0.0     0.0  
3       NaN       NaN     NaN     NaN     NaN  
4     212.0       0.0     0.0     NaN     NaN  

[5 rows x 171 columns]

In [5]:
sensors.dtypes

class      object
aa_000      int64
ab_000    float64
ac_000    float64
ad_000    float64
           ...   
ee_007    float64
ee_008    float64
ee_009    float64
ef_000    float64
eg_000    float64
Length: 171, dtype: object

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.impute import SimpleImputer

In [7]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(sensors, test_size=0.2, random_state=42)

In [8]:
train_set.head()
train_set.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [9]:
num_atts = [col for col in train_set.columns if train_set[col].dtype != 'O' ]
cat_atts = [col for col in train_set.columns if train_set[col].dtype == 'O' ]

In [10]:
num_atts
cat_atts

['class']

In [11]:
simple_imputer = SimpleImputer(strategy="constant", fill_value=0)
robust_scaler = RobustScaler()
num_pipeline = Pipeline(steps=[("Imputer", simple_imputer), ("Robust Scaler", robust_scaler)])

########################## LabelEncoder for Categorical Atts ######################################
label_encoder = LabelEncoder()

########################## Simultaneous Pipeline for both Atts ####################################
full_pipeline = ColumnTransformer([
    ("Numerical Pipeline", num_pipeline, num_atts),
    ("Label Encoder", label_encoder, cat_atts)
])

In [12]:
full_pipeline

ColumnTransformer(transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...]),
                                ('Label Encoder', LabelEncoder(), ['class'])])

In [13]:
X_train = train_set.drop(["class"], axis=1)
y_train = train_set[["class"]]

In [14]:
train_set

class  aa_000  ab_000        ac_000  ad_000  ae_000  af_000  ag_000  \
23601   neg      22     2.0  4.400000e+01     NaN     0.0     0.0     0.0   
4254    neg      10     NaN  0.000000e+00     0.0     0.0     0.0     0.0   
17893   neg   41474     NaN  5.980000e+02     NaN     0.0     0.0     0.0   
16219   neg   18928     NaN  1.406000e+03  1406.0     0.0     0.0     0.0   
13530   neg      26     NaN  2.000000e+01    20.0     0.0     0.0     0.0   
...     ...     ...     ...           ...     ...     ...     ...     ...   
16850   neg  180262     NaN  0.000000e+00     NaN     0.0     0.0     0.0   
6265    neg   39754     NaN  4.900000e+02   466.0     0.0     0.0     0.0   
11284   neg    1798     NaN  4.400000e+01    36.0     0.0     0.0     0.0   
860     neg  179692     0.0  2.130706e+09   704.0    18.0    34.0     0.0   
15795   neg   30766     NaN  5.260000e+02   506.0     0.0     0.0     0.0   

       ag_001  ag_002  ...     ee_002    ee_003     ee_004     ee_005  \
23601     0.0  3454.0  ...      196.0      34.0       46.0       24.0   
4254      0.0     0.0  ...       36.0      26.0       36.0       46.0   
17893     0.0     0.0  ...   331610.0  177770.0   348412.0   315844.0   
16219     0.0     0.0  ...    58134.0    5134.0     1764.0       92.0   
13530     0.0     0.0  ...      508.0      76.0       72.0        0.0   
...       ...     ...  ...        ...       ...        ...        ...   
16850     0.0     0.0  ...  1519772.0  988792.0  3290222.0  1440160.0   
6265      0.0     0.0  ...   181658.0   96452.0   270364.0   344880.0   
11284     0.0     0.0  ...     9082.0    6750.0    16788.0    12258.0   
860       0.0     0.0  ...   486262.0  254052.0   394340.0   308248.0   
15795     0.0     0.0  ...   181734.0   88012.0   194604.0   396336.0   

         ee_006     ee_007    ee_008   ee_009  ef_000  eg_000  
23601      10.0        0.0       0.0      0.0     0.0     0.0  
4254      100.0       26.0       0.0      0.0     0.0     0.0  
17893  237834.0   148534.0  258180.0  15748.0     0.0     0.0  
16219      14.0        0.0       0.0      0.0     0.0     0.0  
13530       0.0        0.0       0.0      0.0     0.0     0.0  
...         ...        ...       ...      ...     ...     ...  
16850  588876.0   259714.0  385322.0  31364.0     0.0     0.0  
6265   382150.0   238500.0  192166.0   1652.0     0.0     0.0  
11284   10300.0     8948.0   14866.0    140.0     0.0     0.0  
860    926104.0  1086352.0   18538.0      0.0     0.0     0.0  
15795  181866.0   113420.0  166686.0  17838.0     0.0     0.0  

[28950 rows x 171 columns]

In [15]:
full_pipeline.fit(X_train)

ValueError: A given column is not a column of the dataframe

In [16]:
num_pipeline.fit(train_set[num_atts])

Pipeline(steps=[('Imputer', SimpleImputer(fill_value=0, strategy='constant')),
                ('Robust Scaler', RobustScaler())])

In [17]:
num_pipeline.transform(X_train[num_atts])

array([[-6.30822265e-01,  2.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.31065599e-01,  0.00000000e+00, -1.40776699e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09733347e-01,  0.00000000e+00,  5.84951456e-01, ...,
         8.04290092e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.94808882e-01,  0.00000000e+00, -8.73786408e-02, ...,
         7.15015322e-02,  0.00000000e+00,  0.00000000e+00],
       [ 3.01249113e+00,  0.00000000e+00,  2.58580864e+06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.40139917e-03,  0.00000000e+00,  4.97572816e-01, ...,
         9.11031665e+00,  0.00000000e+00,  0.00000000e+00]])

In [18]:
label_encoder.fit_transform(y_train[cat_atts])

c:\Users\Admin\anaconda3\envs\sensor\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 0, 0])

In [19]:
full_pipeline.fit_transform(train_set[num_atts], train_set[cat_atts])

ValueError: A given column is not a column of the dataframe

In [20]:
full_pipeline2 =  ColumnTransformer([
    ("Label Encoder", label_encoder, cat_atts),
    ("Numerical Pipeline", num_pipeline, num_atts)    
])
full_pipeline2

ColumnTransformer(transformers=[('Label Encoder', LabelEncoder(), ['class']),
                                ('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...])])

In [21]:
full_pipeline2.fit(train_set)

TypeError: fit_transform() takes 2 positional arguments but 3 were given

In [22]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit_transform(train_set[cat_atts])

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [23]:
full_pipeline3 = ColumnTransformer([
    ("Numerical Pipeline", num_pipeline, num_atts), 
    ("Ordinal Encoder", OrdinalEncoder(), cat_atts)
])
full_pipeline3

ColumnTransformer(transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...]),
                                ('Ordinal Encoder', OrdinalEncoder(),
                                 ['class'])])

In [24]:
train_arr = full_pipeline3.fit_transform(train_set)
train_arr

array([[-6.30822265e-01,  2.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.31065599e-01,  0.00000000e+00, -1.40776699e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09733347e-01,  0.00000000e+00,  5.84951456e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.94808882e-01,  0.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.01249113e+00,  0.00000000e+00,  2.58580864e+06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.40139917e-03,  0.00000000e+00,  4.97572816e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [25]:
train_arr.shape


(28950, 171)

In [26]:
train_set.shape

(28950, 171)

### LabelEncoder() vs OrdinalEncoder()

both have the same functionality. A bit difference is the idea behind. OrdinalEncoder is for converting features, while LabelEncoder is for converting target variable.

That's why OrdinalEncoder can fit data that has the shape of (n_samples, n_features) while LabelEncoder can only fit data that has the shape of (n_samples,) (though in the past one used LabelEncoder within the loop to handle what has been becoming the job of OrdinalEncoder now)

In [41]:
train_arr

array([[-6.30822265e-01,  2.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.31065599e-01,  0.00000000e+00, -1.40776699e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09733347e-01,  0.00000000e+00,  5.84951456e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.94808882e-01,  0.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.01249113e+00,  0.00000000e+00,  2.58580864e+06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.40139917e-03,  0.00000000e+00,  4.97572816e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [44]:
np.savetxt(open('train_arr.txt', 'w'), train_arr)

In [56]:
target = pd.DataFrame(train_set.iloc[:, 0])

In [57]:
enc = OrdinalEncoder()
encoded_target = enc.fit(target)
encoded_target

OrdinalEncoder()

In [58]:
encoded_target.transform(target)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [73]:
full_pipeline3 = ColumnTransformer([
    ("Numerical Pipeline", num_pipeline, num_atts), 
    ("Ordinal Encoder", OrdinalEncoder(), cat_atts)
])
full_pipeline3

ColumnTransformer(transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...]),
                                ('Ordinal Encoder', OrdinalEncoder(),
                                 ['class'])])

In [76]:
full_pipeline3.fit(train_set)

ColumnTransformer(transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...]),
                                ('Ordinal Encoder', OrdinalEncoder(),
                                 ['class'])])

In [77]:
full_pipeline3.transform(train_set)

array([[-6.30822265e-01,  2.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.31065599e-01,  0.00000000e+00, -1.40776699e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09733347e-01,  0.00000000e+00,  5.84951456e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.94808882e-01,  0.00000000e+00, -8.73786408e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.01249113e+00,  0.00000000e+00,  2.58580864e+06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.40139917e-03,  0.00000000e+00,  4.97572816e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [80]:
train_num = num_pipeline.fit_transform(train_set.drop(columns=["class"]))
train_num.shape

(28950, 170)

In [95]:
train_df_num = pd.DataFrame(train_num)
train_df_num.to_csv('traindf_num.csv', index=None)

In [96]:
train_df = pd.DataFrame(train_arr)
train_df.to_csv('traindf.csv', index=None)

In [85]:
train_df.head()

0    1         2         3    4    5    6    7       8       9    ...  \
0 -0.630822  2.0 -0.087379 -0.138169  0.0  0.0  0.0  0.0  3454.0  5468.0  ...   
1 -0.631066  0.0 -0.140777 -0.138169  0.0  0.0  0.0  0.0     0.0     0.0  ...   
2  0.209733  0.0  0.584951 -0.138169  0.0  0.0  0.0  0.0     0.0     0.0  ...   
3 -0.247450  0.0  1.565534  4.718480  0.0  0.0  0.0  0.0     0.0     0.0  ...   
4 -0.630741  0.0 -0.116505 -0.069085  0.0  0.0  0.0  0.0     0.0     0.0  ...   

        161       162       163       164       165       166       167  168  \
0 -0.510374 -0.474944 -0.471981 -0.330238 -0.245357 -0.027335  0.000000  0.0   
1 -0.510411 -0.474965 -0.471927 -0.329914 -0.245204 -0.027335  0.000000  0.0   
2  0.294651  0.264527  0.306422  0.525199  0.632957  1.807659  8.042901  0.0   
3 -0.487275 -0.471297 -0.471814 -0.330224 -0.245357 -0.027335  0.000000  0.0   
4 -0.510184 -0.474889 -0.472040 -0.330274 -0.245357 -0.027335  0.000000  0.0   

   169  170  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0  
4  0.0  0.0  

[5 rows x 171 columns]

In [88]:
train_df_num.head()

0    1         2         3    4    5    6    7       8       9    ...  \
0 -0.630822  2.0 -0.087379 -0.138169  0.0  0.0  0.0  0.0  3454.0  5468.0  ...   
1 -0.631066  0.0 -0.140777 -0.138169  0.0  0.0  0.0  0.0     0.0     0.0  ...   
2  0.209733  0.0  0.584951 -0.138169  0.0  0.0  0.0  0.0     0.0     0.0  ...   
3 -0.247450  0.0  1.565534  4.718480  0.0  0.0  0.0  0.0     0.0     0.0  ...   
4 -0.630741  0.0 -0.116505 -0.069085  0.0  0.0  0.0  0.0     0.0     0.0  ...   

        160       161       162       163       164       165       166  \
0 -0.530986 -0.510374 -0.474944 -0.471981 -0.330238 -0.245357 -0.027335   
1 -0.531347 -0.510411 -0.474965 -0.471927 -0.329914 -0.245204 -0.027335   
2  0.217187  0.294651  0.264527  0.306422  0.525199  0.632957  1.807659   
3 -0.400190 -0.487275 -0.471297 -0.471814 -0.330224 -0.245357 -0.027335   
4 -0.530282 -0.510184 -0.474889 -0.472040 -0.330274 -0.245357 -0.027335   

        167  168  169  
0  0.000000  0.0  0.0  
1  0.000000  0.0  0.0  
2  8.042901  0.0  0.0  
3  0.000000  0.0  0.0  
4  0.000000  0.0  0.0  

[5 rows x 170 columns]

In [89]:
train_df.iloc[:, -1]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
28945    0.0
28946    0.0
28947    0.0
28948    0.0
28949    0.0
Name: 170, Length: 28950, dtype: float64

In [93]:
train_df_num.iloc[:, -1]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
28945    0.0
28946    0.0
28947    0.0
28948    0.0
28949    0.0
Name: 169, Length: 28950, dtype: float64

In [94]:
train_arr[-1]

array([-7.40139917e-03,  0.00000000e+00,  4.97572816e-01,  1.60967185e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -6.73441383e-02, -1.28482705e-01,
        8.22472455e-02,  7.84158256e-01,  1.09485346e+00,  5.11392405e+00,
       -1.69721985e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -1.05332853e-01, -9.31317844e-02,
       -1.60266715e-01, -1.44522434e-02,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.03333333e-01,  3.96694215e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.47046876e-01,  6.81605787e-01,
        1.10404676e-01,  0.00000000e+00, -3.43034056e-01, -2.88342033e-02,
       -5.44174136e-02,  6.99167711e-01,  7.04882362e-01, -7.19942744e-02,
       -2.52380952e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.05211364e-01,  

In [102]:
train_df.iloc[:, -1].drop_duplicates()

0     0.0
70    1.0
Name: 170, dtype: float64

In [101]:
train_df_num.iloc[:, -1].drop_duplicates()

0           0.0
27          2.0
50          4.0
89        430.0
169         6.0
1362       12.0
1379       10.0
3856        8.0
4029       40.0
4394       26.0
5010       68.0
5910       56.0
7214       36.0
9057       32.0
9961       14.0
10210      70.0
10412      16.0
14546      20.0
14983      48.0
15727     416.0
16556     182.0
19056      46.0
19065     200.0
19298     222.0
21295     164.0
21345    1146.0
21785      94.0
25706      42.0
26995     102.0
27311      72.0
27312      24.0
28489     108.0
28527      80.0
Name: 169, dtype: float64

In [105]:
np.unique(train_arr[-1])

array([-5.53962328e-01, -3.43034056e-01, -2.93149529e-01, -2.52764264e-01,
       -2.05211364e-01, -1.86746666e-01, -1.80467054e-01, -1.69875252e-01,
       -1.69721985e-01, -1.63690476e-01, -1.60266715e-01, -1.59051834e-01,
       -1.51664508e-01, -1.43257082e-01, -1.40398753e-01, -1.36738966e-01,
       -1.36404450e-01, -1.28482705e-01, -1.21692817e-01, -1.21160951e-01,
       -1.14331401e-01, -1.11892673e-01, -1.05332853e-01, -1.04163044e-01,
       -9.72070291e-02, -9.31317844e-02, -8.64682007e-02, -7.19942744e-02,
       -7.17100008e-02, -6.73441383e-02, -6.61975075e-02, -6.19589813e-02,
       -5.65448803e-02, -5.44174136e-02, -4.88281879e-02, -2.88342033e-02,
       -2.52380952e-02, -2.39535720e-02, -1.44522434e-02, -1.12820513e-02,
       -8.74498763e-03, -7.40139917e-03, -7.15948072e-03, -6.10429626e-03,
        0.00000000e+00,  3.35965862e-03,  2.02815528e-02,  2.12676461e-02,
        2.46605361e-02,  7.54903940e-02,  8.07570563e-02,  8.22472455e-02,
        8.76474597e-02,  

### Resampling:

In [106]:
from imblearn.combine import SMOTETomek

smt = SMOTETomek(sampling_strategy='minority')
smt

SMOTETomek(sampling_strategy='minority')

In [108]:
X = train_arr[:-1]
y = train_arr[-1]

In [107]:
smt.fit_resample(train_arr)

TypeError: fit_resample() missing 1 required positional argument: 'y'

In [124]:
ordinal_enc = OrdinalEncoder()
ordinal_enc.fit(target)

OrdinalEncoder()

In [125]:
ordinal_enc.categories_

[array(['neg', 'pos'], dtype=object)]

In [127]:
ordinal_enc.transform(target)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [128]:
ordinal_enc.categories_

[array(['neg', 'pos'], dtype=object)]

In [129]:
from sklearn.preprocessing import OneHotEncoder

onehot_enc = OneHotEncoder()
onehot_enc.fit(target)

OneHotEncoder()

In [130]:
onehot_enc.transform(target)

<28950x2 sparse matrix of type '<class 'numpy.float64'>'
	with 28950 stored elements in Compressed Sparse Row format>

In [165]:
full_pipeline4 = ColumnTransformer([
    ("Numerical Pipeline", num_pipeline, num_atts), 
    ("1Hot Encoder", OneHotEncoder(drop="first", sparse=False, dtype='int64'), cat_atts)
])
full_pipeline4

ColumnTransformer(transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value=0,
                                                                strategy='constant')),
                                                 ('Robust Scaler',
                                                  RobustScaler())]),
                                 ['aa_000', 'ab_000', 'ac_000', 'ad_000',
                                  'ae_000', 'af_000', 'ag_000', 'ag_001',
                                  'ag_002', 'ag_003', 'ag_004', 'ag_005',
                                  'ag_006', 'ag_007', 'ag_008', 'ag_009',
                                  'ah_000', 'ai_000', 'aj_000', 'ak_000',
                                  'al_000', 'am_0', 'an_000', 'ao_000',
                                  'ap_000', 'aq_000', 'ar_000', 'as_000',
                                  'at_000', 'au_000', ...]),
                                ('1Hot Encoder',
                                 OneHotEncoder(drop='first', dtype='int64',
                                               sparse=False),
                                 ['class'])])

In [166]:
train_1hot = full_pipeline4.fit_transform(train_set)
train_1hot.shape

(28950, 171)

In [167]:
train_1hot_df = pd.DataFrame(train_1hot)
train_1hot_df.iloc[:, -1].drop_duplicates()

0     0.0
70    1.0
Name: 170, dtype: float64

In [168]:
train_set.shape
np.unique(train_1hot[-1])

array([-5.53962328e-01, -3.43034056e-01, -2.93149529e-01, -2.52764264e-01,
       -2.05211364e-01, -1.86746666e-01, -1.80467054e-01, -1.69875252e-01,
       -1.69721985e-01, -1.63690476e-01, -1.60266715e-01, -1.59051834e-01,
       -1.51664508e-01, -1.43257082e-01, -1.40398753e-01, -1.36738966e-01,
       -1.36404450e-01, -1.28482705e-01, -1.21692817e-01, -1.21160951e-01,
       -1.14331401e-01, -1.11892673e-01, -1.05332853e-01, -1.04163044e-01,
       -9.72070291e-02, -9.31317844e-02, -8.64682007e-02, -7.19942744e-02,
       -7.17100008e-02, -6.73441383e-02, -6.61975075e-02, -6.19589813e-02,
       -5.65448803e-02, -5.44174136e-02, -4.88281879e-02, -2.88342033e-02,
       -2.52380952e-02, -2.39535720e-02, -1.44522434e-02, -1.12820513e-02,
       -8.74498763e-03, -7.40139917e-03, -7.15948072e-03, -6.10429626e-03,
        0.00000000e+00,  3.35965862e-03,  2.02815528e-02,  2.12676461e-02,
        2.46605361e-02,  7.54903940e-02,  8.07570563e-02,  8.22472455e-02,
        8.76474597e-02,  

In [152]:
enc2 = OrdinalEncoder(dtype=int)

In [30]:
transformed_train_arr = full_pipeline3.fit_transform(train_set)

In [31]:
transformed_train_arr[-1]

array([-7.40139917e-03,  0.00000000e+00,  4.97572816e-01,  1.60967185e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -6.73441383e-02, -1.28482705e-01,
        8.22472455e-02,  7.84158256e-01,  1.09485346e+00,  5.11392405e+00,
       -1.69721985e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -1.05332853e-01, -9.31317844e-02,
       -1.60266715e-01, -1.44522434e-02,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.03333333e-01,  3.96694215e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.47046876e-01,  6.81605787e-01,
        1.10404676e-01,  0.00000000e+00, -3.43034056e-01, -2.88342033e-02,
       -5.44174136e-02,  6.99167711e-01,  7.04882362e-01, -7.19942744e-02,
       -2.52380952e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.05211364e-01,  

In [34]:
np.unique(transformed_train_arr[:, -1])

array([0., 1.])